### ISSUE TITLE
Disable `-b` (`--bookmark`) startup option when running in multi-session mode

### ISSUE THREAD

**Issue by sosedoff** [sosedoff/pgweb#295]
Bookmark option should be disabled (or ignored) when starting pgweb in multi-session mode. This causes panic:

```
Pgweb v0.9.9 (git: 4cacfc253c722fc7724e4c688693576dd4a7401d)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1454014]

goroutine 1 [running]:
github.com/sosedoff/pgweb/pkg/cli.initClientUsingBookmark(0xc420137460, 0x20, 0x7fff5fbff5c4, 0x3, 0x10b512b, 0xc4200d60c0, 0xc4201545c0)
	/Users/sosedoff/go/src/github.com/sosedoff/pgweb/pkg/cli/cli.go:48 +0x264
github.com/sosedoff/pgweb/pkg/cli.initClient()
	/Users/sosedoff/go/src/github.com/sosedoff/pgweb/pkg/cli/cli.go:64 +0x105
github.com/sosedoff/pgweb/pkg/cli.Run()
	/Users/sosedoff/go/src/github.com/sosedoff/pgweb/pkg/cli/cli.go:184 +0x2b
main.main()
	/Users/sosedoff/go/src/github.com/sosedoff/pgweb/main.go:8 +0x20
```

**Comment by cristianoliveira** [comment]
I'll take it

**Comment by sosedoff** [comment]
@cristianoliveira any progress? regarding the panic, its actually not related to bookmarks, there was a bug with nil ssh info on the bookmark struct which i already fixed in master.

**Comment by cristianoliveira** [comment]
Hey @sosedoff Sorry. I couldn't take a look into it already. Do you think some change regarding this  `pgweb/pkg/cli/cli.go` is still necessary? If so I can take a look later or other day

**Comment by sosedoff** [comment]
@cristianoliveira i fixed this in #300

**Comment by cristianoliveira** [comment]
Ahh great! :)

**Comment by sosedoff** [comment]
Im closing this since the fix has been merged to master
